#!/bin/bash

# iptables
# Written by Aaron Bach

# Init script that loads custom firewall rules into IPTables.
# Pulls rules from /etc/security/iptables-rules.

# Source the logging functions
. /lib/lsb/init-functions

# Common variables
RETVAL=0
IPTABLES="/sbin/iptables"
IPTABLES_RESTORE="/sbin/iptables-restore"
IPTABLES_RULES="/etc/security/iptables-rules"

# Function definitions
function startIpTables {
	$IPTABLES_RESTORE $IPTABLES_RULES
	return $RETVAL
}

function stopIpTables {
	$IPTABLES -F
	$IPTABLES -X
	$IPTABLES -P INPUT ACCEPT	
	$IPTABLES -P FORWARD ACCEPT	
	$IPTABLES -P OUTPUT ACCEPT	
	return $RETVAL
}

function statusIpTables {
	$IPTABLES -L -n -v
	return $RETVAL
}	

# If not executed as root, kick the user
# out.
if [ $UID != 0 ]; then
	echo "Must be root to run command"
	exit 1;
fi

# If the rules files does not exist, kick
# the user out.
if [ ! -e /etc/security/iptables-rules ]; then
	echo "File does not exist: /etc/security/iptables-rules"
	exit 1;
fi

case "$1" in
	start)
		log_begin_msg "Starting IPTables..."
		startIpTables;
		log_end_msg $RETVAL
		;;
	stop)		
		log_begin_msg "Stopping IPTables..."
		stopIpTables
		log_end_msg $RETVAL
		;;
	restart)
		log_begin_msg "Restarting IPTables..."
		stopIpTables
		startIpTables
		log_end_msg $RETVAL
		;;
	status)
		statusIpTables
		;;
	*)
		log_failure_msg "Usages: /etc/init.d/iptables {start|stop|restart|status}"
		exit 1;
		;;
esac
