#!/bin/zsh
########################################################
#------------------- EXPORTS TEMPLATE -----------------#
########################################################

#--------------------------------------------------
#    OS-specific parameters
#--------------------------------------------------
os=${OSTYPE//[0-9.]/}
dir=$(dirname $0)
if [ -f "${dir}/environment/${os}" ]; then
  source ${dir}/environment/${os}
fi

#--------------------------------------------------
#    Exported parameters
#--------------------------------------------------
export DISPLAY=:0
export TZ="America/Denver"
export PAGER='less'
export EDITOR='nano'

#--------------------------------------------------
#    Language parameters
#--------------------------------------------------
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
export LC_CTYPE=C
