#!/bin/zsh
autoload -U compinit
compinit

#--------------------------------------------------
#    OS-specific binds
#--------------------------------------------------
dir=$(dirname $0)
if [ -f "${dir}/binds/${os}" ]; then
  source ${dir}/binds/${os}
fi
