#!/bin/zsh
#-------------------------------------------------------
#   Overview
#-------------------------------------------------------
#   This file exports environment variables.  It figures
#   out what OS we're on and loads vars specific to that
#   OS, as well.

#--------------------------------------------------
#    OS-specific parameters
#--------------------------------------------------
dir=$(dirname $0)
if [ -f "${dir}/environment/${os}" ]; then
  source ${dir}/environment/${os}
fi

#--------------------------------------------------
#    Exported parameters
#--------------------------------------------------
export DISPLAY=:0
export TZ="America/Denver"
export PAGER='less'
export EDITOR='nano'

#--------------------------------------------------
#    Language parameters
#--------------------------------------------------
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
export LC_CTYPE=C

#--------------------------------------------------
#    Hosts
#--------------------------------------------------
export bap='bachya@bachyaproductions.com'
export brep='brepadmin@bachpartners.com'
export wk='aaron@localhost:9999'
export bstar='root@bachya.dnsdojo.com:33077'
export harmonic='aaron@harmonic.cs.colorado.edu'
export fbt='aaronbach@fusionboxtesting.com'
export buggy='aaron@buggy.fusionbox.com'
export fb='agroth@74.52.107.50:2222'
export ft='fitnesst@corp.fitnesstogether.com'
export elements='corptoe@corp.touchofelements.com'
export luminate='luminate@luminatellc.com'
export mvoy='musicvoy@musicvoyager.com'
export cims='fusionbox@69.1.104.68'
export dg='fusionbox@dreamgarage.com'
export nord='nordsted@69.1.104.161'
export fbcom='agroth@74.52.107.50:2222'