#!/bin/zsh
#-------------------------------------------------------
#   Overview
#-------------------------------------------------------
#   Custom functions (generic and OS-specific) are
#   defined here.

#--------------------------------------------------
#    OS-specific functions
#--------------------------------------------------
dir=$(dirname $0)
if [ -f "${dir}/functions.d/${os}" ]; then
  source ${dir}/functions.d/${os}
fi

#-------------------------------------------------------
#    Create an archive from a set of files
#-------------------------------------------------------
archive()
{
  if [ "$#" -ne 2 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Usage: archive [--tgz --zip --7z] [path/to/directory]" >&2
    return 1
  fi
  
  if [ ! -d $2 ]; then
    echo "$2 is not a valid directory of files"
    return 1
  else
    arch_base_name=$(basename $2)
    case $1 in
      --tgz)  tar cvf ${arch_base_name}.tar.gz $2 ;;
      --zip)  zip ${arch_base_name}.zip $2        ;;
      --7z)   7za a ${arch_base_name}.7z $2       ;;
      *)                                          ;;  
    esac
  fi
}

#-------------------------------------------------------
#    Extract files from an archive
#-------------------------------------------------------
extract() 
{
  if [ "$#" -ne 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Usage: extract [archive]" >&2
    return 1
  fi
  
  if [ -f $1 ]; then
    case $1 in
      *.tar.bz2)  tar xvjf $1     ;;
      *.tbz)      tar xvjf $1     ;;
      *.tar.gz)   tar xvzf $1     ;;
      *.bz2)      bunzip2 $1      ;;
      *.gz)       gunzip $1       ;;
      *.tar)      tar xvf $1      ;;
      *.tbz2)     tar xvjf $1     ;;
      *.tgz)      tar xvzf $1     ;;
      *.zip)      unzip $1        ;;
      *.7z)       7za x $1        ;;
      *)          echo "'$1' is not a valid archive" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

#-------------------------------------------------------
#    Wrapper for ps auwxx that removes the 'grep'
#    result
#-------------------------------------------------------
process() 
{
  if [ "$#" -ne 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Usage: process [process-name]" >&2
    return 1
  fi
  
  ps auwxx | grep -i "$1" | grep -v grep
}

#-------------------------------------------------------
#    Switches the names of two files
#-------------------------------------------------------
switch() 
{
  if [ "$#" -ne 2 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Usage: switch [file1] [file2]" >&2
    return 1
  fi

  echo "* Switching '${1}' and '${2}'..." 
  mv $1 ${1}.tmp && mv $2 $1 && mv ${1}.tmp $2
  echo "* Files switched!"
}

#-------------------------------------------------------
#    Performs a 'cd ../' n times (where n is given)
#-------------------------------------------------------
up()
{
  if [ "$#" -gt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Usage: up [number-of-dirs]" >&2
    return 1
  fi
  
  local arg=${1:-1}
  local dir=""
  while [ $arg -gt 0 ]; do
    dir="../${dir}"
    arg=$(($arg - 1));
  done
  cd $dir >&/dev/null
}

#-------------------------------------------------------
#    Determines whether a function is recognized by
#    the shell
#-------------------------------------------------------
fn_exists()
{
  type $1 | grep -q 'shell'
}
