#!/bin/zsh
#--------------------------------------------------
#  Linux-specific exports    
#--------------------------------------------------
ANDROID_PATH=/home/aaron/Code/android-sdk-linux_86/tools
export PATH=${ANDROID_PATH}:${PATH}