#!/bin/zsh
######################################################################
#  AMB .zshrc file
######################################################################
autoload colors zsh/terminfo
os=${OSTYPE//[0-9.]/}

for zshrc_snipplet in ~/.zsh.d/S[0-9][0-9]*[^~] ; do
  source $zshrc_snipplet
done

if [[ "$terminfo[colors]" -ge 8 ]]; then
  colors
fi
for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
  eval PR_$color='%{$terminfo[bold]$fg[${(L)color}]%}'
  eval PR_LIGHT_$color='%{$fg[${(L)color}]%}'
  (( count = $count + 1 ))
done

PR_NO_COLOR="%{$terminfo[sgr0]%}"

git_br='$(get_git_prompt_info "%b")'
git_dirty='$(get_git_prompt_info "%s")'
r_prompt="($PR_GREEN$git_br$PR_RED$git_dirty$PR_NO_COLOR)"

PS1="[$PR_BLUE%n$PR_NO_COLOR@$PR_GREEN%U%m%u$PR_NO_COLOR:$PR_RED%2c$PR_NO_COLOR]%(!.#.$) "
RPS1=$r_prompt