#!/bin/zsh
######################################################################
#  AMB .zshrc file
######################################################################
autoload colors zsh/terminfo

for zshrc_snipplet in ~/.zsh.d/S[0-9][0-9]*[^~] ; do
  source $zshrc_snipplet
done

if [[ "$terminfo[colors]" -ge 8 ]]; then
  colors
fi
for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
  eval PR_$color='%{$terminfo[bold]$fg[${(L)color}]%}'
  eval PR_LIGHT_$color='%{$fg[${(L)color}]%}'
  (( count = $count + 1 ))
done

git_b='$(get_git_prompt_info '%b')'
PR_NO_COLOR="%{$terminfo[sgr0]%}"
PS1="[$PR_BLUE%n$PR_NO_COLOR@$PR_GREEN%U%m%u$PR_NO_COLOR:$PR_RED%2c$PR_NO_COLOR:$PR_MAGENTA$git_b$PR_NO_COLOR]%(!.#.$) "
RPS1="$PR_MAGENTA(%D{%Y-%m-%d %l:%M %p})$PR_NO_COLOR"