#!/bin/zsh

if test -x dircolors; then
    eval "`dircolors`"
    export LS_COLORS="*.ogm=01;35:${LS_COLORS}"
    export ZLS_COLORS=$LS_COLORS
fi

autoload -U is-at-least

#[ a ]########################################################################################
setopt aliases              # Expand aliases.
setopt all_export           # All parameters subsequently defined are automatically 
														# exported.
setopt always_to_end        # The cursor is moved to the end of the word if either
														# a single match is inserted or menu completion is 
														# performed.
setopt append_history       # zsh sessions will append their history list to the 
														# history file, rather than overwrite it.
setopt auto_cd              # Do cd path if only 'path' is given as command.
setopt auto_continue        # Send SIGCONT to disowned jobs.
setopt auto_list            # Automatically list choices on an ambiguous completion.
setopt auto_menu            # Show menu for completion.
setopt no_autoname_dirs     # After foo=/absolute/path, ~foo may expand to
                            # /absolute/path, but `%~' in prompt won't give
                            # `~foo' until `~foo' has been used (RTFM closely).
setopt auto_param_keys      # Remove trailing spaces after completion (if needed).
setopt auto_param_slash     # Auto add slash for directories.
setopt auto_pushd           # Make cd push the old dir onto the dir stack.
setopt auto_remove_slash    # Remove slash on dirs if word separator added.
setopt auto_resume          # Treat single word simple commands without redirection 
														# as candidates for resumption of an existing job.

#[ b ]########################################################################################
setopt bad_pattern          # Error if a pattern for filename generation is badly 
														# formed.
setopt bang_hist            # Perform textual history expansion, csh-style,
														# treating the character `!' specially.
setopt bare_glob_qual       # In a glob pattern, treat a trailing set of parentheses
														# as a qualifier list, if it contains no `|', `(' or 
														# (if special) `~' characters.
setopt no_bash_auto_list    # Auto_list is sufficient (I want it on first tab).
setopt no_bg_nice           # Don't run all background jobs at a lower priority.
setopt brace_ccl            # Expand expressions in braces which would not otherwise
														# undergo brace expansion to a lexically ordered list of
														# all the characters.
setopt no_bsd_echo          # BSD-compatible echo not needed.

#[ c ]########################################################################################
setopt case_glob            # Make globbing (filename generation) sensitive to case.
setopt c_bases              # Output hexadecimal numbers in the standard C format, 
														# for example `0xFF' instead of the usual `16#FF'.
setopt no_cdable_vars       # Don't automagically add ~ to paths w/o a starting /.
setopt no_chase_dots        # foo/bar/.. is foo/ even if bar is a symlink.
setopt chase_links          # cd to a symlink = cd to the true dir.
setopt check_jobs           # Report the status of background and suspended jobs 
														# before exiting a shell with job control.
setopt clobber              # Allows `>' redirection to truncate existing files, 
														# and `>>' to create files.
setopt complete_aliases     # Prevents aliases on the command line from being 
														# internally substituted before completion is attempted
setopt complete_in_word     # Start completion from current cursor location.
setopt correct              # Try to correct the spelling of commands.
setopt no_correct_all       # Don't try to correct the spelling of all arguments in a line.
setopt no_csh_junkiehistory # Don't want this.
setopt no_csh_junkie_loops  # Stick with `do list; done'.
setopt no_csh_junkie_quotes # Don't rewire quote rules to match csh.
setopt no_csh_nullcmd       # We want to keep my (READ)?NULLCMD settings.
setopt no_csh_null_glob     # Don't silently erase unmatched globs.

#[ d-g ]######################################################################################
setopt no_dvorak            # Don't use the Dvorak keyboard layout.
setopt no_emacs             # Use bindkeys rather than this deprecated feature.
setopt equals               # Perform = filename expansion.
setopt no_err_exit          # Don't want to see exit status (even if non-zero).
setopt no_err_return        # Don't immediately return from the enclosed function
														# if a command has a non-zero exit status).
setopt exec                 # We actually want to execute commands (and not just
														# check them for correctness).
setopt extended_glob        # Treat the `#', `~' and `^' characters as part of 
                            # patterns for filename generation, etc.
setopt no_extended_history  # Regular history (don't save beginning timestamp).
setopt no_flow_control      # Ignore/Disable ^S/^Q.
setopt function_argzero     # When executing a shell function or sourcing a script,
                            # set $0 temporarily to the name of the function/script.
setopt glob                 # Perform filename generation (globbing).
setopt no_global_export     # Local vars are not made global.
setopt global_rcs           # The startup files /etc/zprofile, /etc/zshrc, /etc/zlogin 
                            # and /etc/zlogout will not be run.
setopt no_glob_assign       # No globbing on foo=* - use foo=(*).
setopt no_glob_complete     # Don't generate glob matches and cycle through them.
setopt no_glob_dots         # Do not require a leading `.' in a filename to be matched explicitly.
setopt no_glob_subst        # No recursive expansion.

#[ h-j ]######################################################################################
setopt hash_cmds            # Note the location of each command the first time it is executed
                            # (don't have to do a path search each time - basically command
                            # caching).
setopt hash_dirs            # Hash directories, too.
setopt hash_list_all        # Whenever a command completion is attempted, make sure the entire 
                            # command path is hashed first. This makes the first completion slower.
setopt hist_allow_clobber   # Add `|' to output redirections in the history.
setopt no_hist_beep         # Beep when an attempt is made to access a history entry which isn't there.
setopt hist_find_no_dups    # Do not display duplicates of a line previously found.
setopt hist_ignore_all_dups # Older command is removed from the list.
setopt no_hist_ignore_space # Hold onto commands in the history that start with spaces.
setopt hist_no_functions    # Remove function definitions from the history list.
setopt hist_no_store        # remove hists access cmds from hist
setopt hist_reduce_blanks   # remove superfluous blanks
setopt hist_save_no_dups    # no dups on history saving
setopt hist_verify          # some expansion gadget
setopt no_hup               # don't SIGHUP bg cmds on logout
setopt no_ignore_braces     # do braces expansion
setopt no_ignore_eof        # don't ignore ^D
setopt no_inc_appendhistory # dont' append incrementally
setopt interactive_comments # allow comments in interactive shell

#[ k-o ]######################################################################################
setopt no_ksh_arrays        # don't emulate ksh arrays
setopt no_ksh_autoload      # don't do some dark autoload on function call
setopt no_ksh_glob          # ignore @ before ()
setopt ksh_option_print     # modify setopt output
setopt no_ksh_typeset       # use zsh typeset
setopt list_ambiguous       # unambiguous prefix completion is done silently
setopt no_list_beep         # don't beep for completion
setopt list_packed          # different width for completion
setopt no_list_rows_first   # sort by colums
setopt list_types           # show types of listing files
setopt long_list_jobs       # list jobs in long format
setopt magic_equal_subst    # foo= is file expanded
setopt no_mail_warning      # auto-explained
setopt mark_dirs            # adds / on dirs in filename completion
setopt no_menu_complete     # don't show menu on ambiguous completion
setopt monitor              # job control
setopt multios              # multi redirection allowed
setopt nomatch              # print error on non matched patterns
setopt notify               # notify immediately, not on next prompt
setopt no_null_glob         # don't delete not matched globs
setopt numeric_glob_sort    # sort in numeric order rather than lexicographic
setopt no_octal_zeroes      # 010 = 9 sucks
setopt no_overstrike        # dont start le in overstrike mode

#[ p-r ]######################################################################################
setopt path_dirs            # search in path even if cmd has '/' in it
setopt no_posix_builtins    # yeah don't like posix, i'm a rebel
setopt print_eight_bit      # just to be sure
setopt no_prompt_bang       # dont perform history expansion in prompt
setopt no_prompt_cr         # don'tprint <cr> before prompt ---> see precmd !
setopt prompt_percent       # expand % escapes in prompt
setopt prompt_subst         # subts in prompt
setopt pushd_ignore_dups    # ignore dups in pushd
setopt pushd_silent         # don't print stack after push/pop
setopt pushd_to_home        # pushd == pushd $HOME
setopt rc_expand_param      # some expansion trick for arrays in params
setopt rc_quotes            # '' == ' in 'quoted exprs
setopt rcs                  # source all /etc rcs
setopt no_rec_exact         # recognize exact match even if ambiguous
setopt no_rm_star_silent    # ask user before rm foo/*
setopt no_rm_star_wait      # dont't idle 10 seconds

#[ s-z ]######################################################################################
setopt no_share_history     # traditional bash-history
setopt no_sh_file_expansion # dont expand filnames first
setopt no_sh_glob           # allow globbing with [(|)<]
setopt no_sh_nullcmd        # use my NULLCMD
setopt sh_option_letters    # interprete single option letters a la ksh
setopt short_loops          # short loops
setopt no_sh_word_split     # `s="a b"; a=($s)' => array of length 1, not 2
setopt no_single_line_zle   # use multiline editor
setopt no_sun_keyboard_hack # i don't use sun kb
setopt transient_rprompt    # better for cut/paste
setopt vi                   # use bindkeys
setopt no_xtrace            # do not debug by default
setopt zle                  # use zsh le

is-at-least 4.3.0 && {
	unsetopt hist_save_by_copy
}

HISTFILE=~/.histfile
HISTSIZE=10000              # size of history
LISTMAX=1000                # never ask
NULLCMD='cat'               # use cat for > null commands
REPORTTIME=2                # report time if execution exceeds amount of seconds
SAVEHIST=10000              # maximum of history events to be save
LOGCHECK=60
watch=(notme)               # watch login/logout
WORDCHARS="*?_-.[]~/&;!#$%^(){}<>"
                            # part of word in line editor
