#!/bin/zsh
########################################################
#------------------ ALIASES TEMPLATE ------------------#
########################################################

#--------------------------------------------------
#    OS-specific aliases
#--------------------------------------------------
dir=$(dirname $0)
if [ -f "${dir}/aliases/${os}" ]; then
  source ${dir}/aliases/${os}
fi

#--------------------------------------------------
#    Bash command aliases
#--------------------------------------------------
alias rf='rm -rf'
alias df='df -H'
alias cl='clear'
alias mv='nocorrect mv'
alias cp='nocorrect cp'
alias mkdir='nocorrect mkdir'
alias rsrc='source ~/.zshrc'

#--------------------------------------------------
#    Bash FBMVC aliases
#--------------------------------------------------
alias fbmvc='./fbmvc'
alias ifb='./fbmvc ifb'
alias gut='git'

#--------------------------------------------------
#    Bash ssh aliases
#--------------------------------------------------
alias bap='ssh bachya@bachyaproductions.com'
alias brep='ssh brepadmin@bachpartners.com'
alias wk='ssh -p 9999 aaron@localhost'
alias bstar='ssh -p 33077 root@bachya.dnsdojo.com'
alias harmonic='ssh aaron@harmonic.cs.colorado.edu'

#--------------------------------------------------
#    Bash ssh aliases (Fusionbox)
#--------------------------------------------------
alias fb='ssh aaronbach@fusionboxtesting.com'
alias buggy='ssh aaron@buggy.fusionbox.com'
alias fbcom='ssh -p 2222 agroth@74.52.107.50'
alias ft='ssh fitnesst@corp.fitnesstogether.com'
alias elements='ssh corptoe@corp.touchofelements.com'
alias luminate='ssh luminate@luminatellc.com'
alias mvoy='ssh musicvoy@musicvoyager.com'
alias cims='ssh fusionbox@69.1.104.68'
alias dg='ssh fusionbox@dreamgarage.com'
